apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: amd-xilinx-tools-rook
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 300Gi
