apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amd-xilinx-tools
spec:
  storageClassName: seaweedfs-storage-nvme
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
