apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amd-xilinx-tools-rook
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
