apiVersion: batch/v1
kind: Job
metadata:
  name: wa-hls4ml-search-pregen-2layer-test
  labels:
    jobgroup: wa-hls4ml-search
spec:
  template:
    spec:
      containers:
      - name: hls4ml-docker
        image:  bhawks/wa-hls4ml-search:centos81-vivado-2020.1-minimal
        terminationMessagePolicy: FallbackToLogsOnError
        command: ["/bin/bash"]
        args:
          - -l
          - -c
          - >-
              cat /home/vivado/.bashrc &&
              source /venv/bin/activate && 
              echo "activated venv" &&
              source /opt/Xilinx/Vivado/2020.1/settings64.sh &&
              echo "Setup Vivado, running job..." &&
              python /opt/repo/wa-hls4ml-search/iter_manager.py
              -f /opt/repo/wa-hls4ml-search/pregen_2layer_models/filelist_1.csv
              -o /output/2layer_run_vsynth_test
              --hls4ml_strat resource
              --rf_upper 4097
              --rf_lower 1024
              --rf_step 1024
              --vsynth
        volumeMounts:
        - name: amd-xilinx-tools-rook
          mountPath: /opt/Xilinx
        - name: git-repo
          mountPath: /opt/repo
        - name: wa-search-output
          mountPath: /output
        resources:
          limits:
            memory: 32Gi
            cpu: "2.4"
          requests:
            memory: 32Gi
            cpu: "2"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command: ["/bin/sh"]
        args:
          - -l
          - -c
          - >-
              if cd /opt/repo/wa-hls4ml-search; 
              then git pull; 
              else git clone https://github.com/ben-hawks/wa-hls4ml-search -b main /opt/repo/wa-hls4ml-search;
              fi
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
        resources:
          limits:
            memory: 8Gi
            cpu: "2.4"
          requests:
            memory: 7Gi
            cpu: "2"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-west
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: NotIn
                    values:
                      - "true"
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                      - ucsd-nrp
      volumes:
      - name: amd-xilinx-tools-rook
        persistentVolumeClaim:
          claimName: amd-xilinx-tools-rook
      - name: wa-search-output
        persistentVolumeClaim:
          claimName: wa-search-output
      - name: git-repo
        persistentVolumeClaim:
            claimName: wa-search-git
      restartPolicy: Never
  backoffLimit: 5