apiVersion: batch/v1
kind: Job
metadata:
  name: wa-hls4ml-search-update-model-json-2layer
  labels:
    jobgroup: wa-hls4ml-search
spec:
  template:
    spec:
      containers:
      - name: hls4ml-docker
        image:  ghcr.io/ben-hawks/wa-hls4ml-search:v2023.2
        terminationMessagePolicy: FallbackToLogsOnError
        command: ["/tini", "--", "/bin/bash"]
        env:
          - name: LD_PRELOAD
            value: /lib/x86_64-linux-gnu/libudev.so.1
        args:
          - -l
          - -c
          - >-
              cat /home/xilinx/.bashrc &&
              source /venv/bin/activate && 
              echo "activated venv" &&
              source /tools/Xilinx/Vitis/2023.2/settings64.sh &&
              echo "Setup Vivado, running job..." &&
              cd /output/2layer_run_vsynth_2023-2 &&
              python /opt/repo/wa-hls4ml-search/util/update_model_json.py
              . 
              --output-dir ../2layer_run_vsynth_2023-2_updated
              --tar-output ../2layer_run_vsynth_2023-2_updated.tar.gz --max-cores 16
              --verbose
        volumeMounts:
        - name: xilinx-tools
          mountPath: /tools/Xilinx
        - name: git-repo-bkup
          mountPath: /opt/repo
        - name: wa-search-output-backup
          mountPath: /output
        - name: eph-storage
          mountPath: /project
        resources:
          limits:
            memory: 16Gi
            cpu: "16"
            ephemeral-storage: 128Gi
          requests:
            memory: 16Gi
            cpu: "16"
            ephemeral-storage: 128Gi
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command: ["/bin/sh"]
        args:
          - -l
          - -c
          - >-
              if cd /opt/repo/wa-hls4ml-search; 
              then git pull; 
              else git clone https://github.com/ben-hawks/wa-hls4ml-search -b main /opt/repo/wa-hls4ml-search;
              fi
        volumeMounts:
          - name: git-repo-bkup
            mountPath: /opt/repo
        resources:
          limits:
            memory: 8Gi
            cpu: "2"
          requests:
            memory: 8Gi
            cpu: "2"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-central
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: NotIn
                    values:
                      - "true"
      volumes:
      - name: xilinx-tools
        persistentVolumeClaim:
          claimName: xilinx-tools-central
      - name: wa-search-output-backup
        persistentVolumeClaim:
          claimName: wa-search-output-backup
      - name: git-repo-bkup
        persistentVolumeClaim:
            claimName: wa-search-git-bkup
      - name: eph-storage
        emptyDir:
          sizeLimit: 128Gi
      restartPolicy: Never
  backoffLimit: 5