apiVersion: batch/v1
kind: Job
metadata:
  name: wa-hls4ml-search-pregen-3layer-vsynth-46
  labels:
    jobgroup: wa-hls4ml-search
spec:
  template:
    spec:
      containers:
      - name: hls4ml-docker
        image:  ghcr.io/ben-hawks/wa-hls4ml-search:main
        terminationMessagePolicy: FallbackToLogsOnError
        command: ["/tini", "--", "/bin/bash"]
        env:
          - name: LD_PRELOAD
            value: /lib/x86_64-linux-gnu/libudev.so.1
        args:
          - -l
          - -c
          - >-
              cat /home/xilinx/.bashrc &&
              source /venv/bin/activate && 
              echo "activated venv" &&
              source /tools/Xilinx/Vivado/2020.1/settings64.sh &&
              echo "Setup Vivado, running job..." &&
              python /opt/repo/wa-hls4ml-search/iter_manager_v2.py
              -f /opt/repo/wa-hls4ml-search/pregen_3layer_models/filelist_46.csv
              -o /output/3layer_run_vsynth
              --hls4ml_strat resource
              --rf_upper 4097
              --rf_lower 1024
              --rf_step 1024
              --vsynth
        volumeMounts:
        - name: xilinx-tools
          mountPath: /tools/Xilinx
        - name: git-repo-bkup
          mountPath: /opt/repo
        - name: wa-search-output-backup
          mountPath: /output
        resources:
          limits:
            memory: 16Gi
            cpu: "3"
          requests:
            memory: 16Gi
            cpu: "3"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command: ["/bin/sh"]
        args:
          - -l
          - -c
          - >-
              if cd /opt/repo/wa-hls4ml-search; 
              then git pull; 
              else git clone https://github.com/ben-hawks/wa-hls4ml-search -b main /opt/repo/wa-hls4ml-search;
              fi
        volumeMounts:
          - name: git-repo-bkup
            mountPath: /opt/repo
        resources:
          limits:
            memory: 8Gi
            cpu: "2"
          requests:
            memory: 8Gi
            cpu: "2"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-west
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: NotIn
                    values:
                      - "true"
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - ucsd-nrp
      volumes:
      - name: xilinx-tools
        persistentVolumeClaim:
          claimName: xilinx-tools
      - name: wa-search-output-backup
        persistentVolumeClaim:
          claimName: wa-search-output-backup
      - name: git-repo-bkup
        persistentVolumeClaim:
            claimName: wa-search-git-bkup
      restartPolicy: Never
  backoffLimit: 5