services:
  wa-hls4ml:
    image: xilinx-ubuntu-18.04.2-userv2020.1_deploy
    container_name: wa-hls4ml-search-local
    environment:
      LD_PRELOAD: /lib/x86_64-linux-gnu/libudev.so.1
    volumes:
        - /opt/Xilinx:/opt/Xilinx
        - /home/bhawks/hls4ml:/opt/repo
        - /home/bhawks/hls4ml/test_output:/output
