FROM xilinx-ubuntu-20.04.4-user:v2023.2 AS build
LABEL authors="bhawks"

# Install Miniforge
USER root
RUN curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" \
    && bash Miniforge3-$(uname)-$(uname -m).sh -b -p /opt/conda \
    && source "/opt/conda/etc/profile.d/conda.sh" \
    && echo "export PATH=/opt/conda/bin:$PATH" > /etc/profile.d/conda.sh \
USER xilinx
ENV PATH=/opt/conda/bin:$PATH
#setups stuff
RUN echo "source activate base" > ~/.bashrc
#install packages
COPY files/acorn-dac.yml /tmp/acorn-dac.yml
RUN conda env create --name acorn-dac --file /tmp/acorn-dac.yml

RUN conda install -y -c conda-forge conda-pack

RUN conda-pack -n acorn-dac -o /tmp/env.tar && \
  mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
  rm /tmp/env.tar

RUN /venv/bin/conda-unpack

FROM xilinx-ubuntu-20.04.4-user:v2023.2 AS deploy

COPY --from=build --chown=xilinx /venv /venv

USER xilinx
WORKDIR /home/xilinx

RUN echo "source /venv/bin/activate" >> ~/.bashrc
RUN echo "source /opt/Xilinx/petalinux/v2023.2/settings.sh" > ~/.bashrc
RUN echo "source /opt/Xilinx/Vitis/2023.2/settings64.sh" > ~/.bashrc
RUN echo "source /opt/Xilinx/Vivado/2023.2/settings64.sh" > ~/.bashrc
RUN cat ~/.bashrc

ENV LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
ENV XILINXD_LICENSE_FILE=2100@

RUN sudo apt-get update -y && \
    sudo apt-get install --no-install-recommends -y \
    ghdl gtkwave && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*




SHELL ["/bin/bash", "-c", "-l"]
ENTRYPOINT source /venv/bin/activate &&